version: "3.9"

services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
    image: front
    container_name: front
    ports:
      - "3000:3000"
networks:
  default:
    external: true
    name: postgres_network      